- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 15h
      inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  access:
  - Medical
  - Maintenance
  #start-backmen: currency
  minBankBalance: 250 # DS14-value
  maxBankBalance: 350 # DS14-value
  wageDepartment: Medical
  wage: 100 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: Medical
      # DS14-End

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksIntern
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalInternChameleonOutfit
  job: MedicalIntern
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesLatex
