- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Paramedic # DS14
  - Coroner # DS14
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: Medical
      # DS14-End
  #start-backmen: currency
  minBankBalance: 200 # DS14-value
  maxBankBalance: 300 # DS14-value
  wageDepartment: Medical
  wage: 125 # DS14-value
  #end-backmen: currency

- type: startingGear
  id: DoctorGear
  equipment:
    id: MedicalPDA # DS14
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
