- type: job
  id: CentralCommandBlueShieldOfficer
  name: job-name-blue-shield-officer
  description: job-description-blue-shield-officer
  playTimeTracker: JobCentralCommandBlueShieldOfficer
  setPreference: false
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 252000 # 70 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  startingGear: CentcomBlueShieldGear
  icon: "JobIconBlueShieldOfficer"
  supervisors: job-supervisors-centcom-administrator
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand

- type: entity
  parent: ClothingBackpackBlueShield
  id: ClothingBackpackBlueShieldCentComFilled
  name: модифицированный рюкзак офицера "Синий Щит"
  description: Рюкзак офицера "Синий Щит" с функцией РИГ.
  suffix: Заполненный, ЦентКом
  components:
  - type: StorageFill
    contents:
      - id: BoxMRE
      - id: ERTloadoutBlueShieldPrimary
      - id: ADTtelescopicBaton
      - id: TelescopicShield
      - id: MedkitCombatFilled
        amount: 2 
      - id: HandheldCrewMonitor
      - id: Zipties
        amount: 2
      - id: CelestinMedipen
        amount: 2

- type: entity
  id: ClothingBeltMilitaryWebbingBlueShieldCentComFilled
  parent: ClothingBeltMilitaryWebbingBlueShieldFilled
  name: РПС офицера "Синий Щит"
  description: РПС, которую носят офицеры "Синий Щит"
  suffix: Заполненный, ЦентКом
  components:
  - type: StorageFill
    contents:
      - id: JawsOfLife
      - id: PowerDrill
      - id: WelderExperimental
      - id: CombatHypoBlueShield
      - id: ChemistryBottleEphedrine
      - id: ChemistryBottleOmnizine
      - id: ChemistryBottleOmnizine
      - id: ChemistryBottleBicaridine
      - id: ChemistryBottleDexalinPlus
      - id: ChemistryBottleDermaline

- type: startingGear
  id: CentcomBlueShieldGear
  equipment:
    head: ClothingHeadHatBeretBlueShield
    jumpsuit: ClothingUniformJumpsuitBlueShield
    # back: ClothingBackpackBlueShieldCentComFilled
    mask: ClothingMaskGasBlueShield
    eyes: ClothingEyesHudBlueShield
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesBlueShield
    outerClothing: ClothingOuterArmorBasicBlueShield
    shoes: ClothingShoesBootsBlueShield
    id: BlueShieldOfficerPDA
    pocket1: PistolBlueShield
    pocket2: WeaponDisabler
    belt: ClothingBeltMilitaryWebbingBlueShieldCentComFilled
  storage:
    outerClothing:
    - ClothingEyesGlassesMeson
    - DoubleEmergencyOxygenTankFilled
    - PinpointerUniversal


- type: chameleonOutfit
  id: CentralCommandBlueShieldOfficerChameleonOutfit
  job: CentralCommandBlueShieldOfficer
  equipment:
    head: ClothingHeadHatBeretBlueShield
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicBlueShield
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltMilitaryWebbingMed
