- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 4h
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  # DS14-start
  # extendedAccess:
  # - Atmospherics
  # DS14-end
  #start-backmen: currency
  minBankBalance: 200 # DS14-value
  maxBankBalance: 300 # DS14-value
  wageDepartment: Engineering
  wage: 125 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: Engineer
      # DS14-End

- type: startingGear
  id: StationEngineerGear
  equipment:
    id: EngineerPDA # DS14
    eyes: ClothingEyesGlassesMeson
#    belt: ClothingBeltUtilityEngineering # DS14
    ears: ClothingHeadsetEngineering
    socks: ClothingUnderwearSocksEngineer
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: StationEngineerChameleonOutfit
  job: StationEngineer
  equipment:
    head: ClothingHeadHatHardhatYellow
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
