
- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeDominator
  name: dominators safe
  components:
  - type: StorageFill
    contents:
    - id: PistolDominator
      amount: 3

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeVerdict
  name: verdicts safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRevolverVerdict
      amount: 3
    - id: SpeedLoaderMagnum
      amount: 6

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeArmorHeavy
  name: armor heavy safe
  components:
  - type: StorageFill
    contents:
    - id: ClothingOuterArmorHeavy
    - id: ClothingShoesSwat
    - id: ClothingMaskGasSwat
    - id: ClothingHeadHelmetSwat

- type: entity
  id: LockerBlueShieldFilled
  suffix: BlueShield, Filled
  parent: LockerBlueShield
  components:
  - type: StorageFill
    contents:
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
      - id: FlashlightSeclite
      - id: RubberStampBlueShield
      - id: CigarGoldCase
      - id: NanotrasenFlippo
      - id: WeaponDisabler
      - id: ClothingHeadHelmetBlueShield

