- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # 1 hour
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  #start-backmen: currency
  minBankBalance: 250 # DS14-value
  maxBankBalance: 350 # DS14-value
  wageDepartment: Civilian
  wage: 120 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: BaseSkills
      # DS14-End

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
    socks: ClothingUnderwearSocksReporter
  storage:
    back:
    - TapeRecorder
    - CassetteTape
    - CassetteTape

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
