- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 288000 # 80 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance
  #start-backmen: currency
  minBankBalance: 300 # DS14-value
  maxBankBalance: 400 # DS14-value
  wageDepartment: Science
  wage: 250 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
    # DS14-Start
    - type: Skill
      group: HeadScience
    # DS14-End

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    ears: ClothingHeadsetScience
    socks: ClothingUnderwearSocksSeniorResearcher
    id: SeniorResearcherPDA
  storage:
    back:
    - RubberStampSeniorResearcher # DS14

- type: chameleonOutfit
  id: SeniorResearcherChameleonOutfit
  job: SeniorResearcher
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
