- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # 1 hour
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  #start-backmen: currency
  minBankBalance: 200 # DS14-value
  maxBankBalance: 300 # DS14-value
  wageDepartment: Civilian
  wage: 120 # DS14-value
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: MindCaptureDefence #DS14
    # DS14-Start
    - type: Skill
      group: BaseSkills
    # DS14-End

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
    socks: ClothingUnderwearSocksChaplain
  storage:
    back:
    - RubberStampChaplain
    - Censer

- type: chameleonOutfit
  id: ChaplainChameleonOutfit
  job: Chaplain
  equipment:
    head: ClothingHeadHatPlaguedoctor
    eyes: ClothingEyesGlasses
    mask: ClothingMaskPlague
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterPlagueSuit
    gloves: ClothingHandsGlovesColorBlack

