- type: job
  id: Musician
  name: job-name-musician
  description: job-description-musician
  playTimeTracker: JobMusician
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # 1 hour
  startingGear: MusicianGear
  icon: "JobIconMusician"
  supervisors: job-supervisors-hop # Corvax-JobSupervisors
  access:
  - Maintenance # TODO Remove maint access for all gimmick jobs once access work is completed
  - Theatre
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: MikuDay
    prototype: BoxPerformer
  - !type:AddComponentSpecial
    components:
    # DS14-Start
    - type: Skill
      group: BaseSkills
    # DS14-End
  #start-backmen: currency
  minBankBalance: 250 # DS14-value
  maxBankBalance: 350 # DS14-value
  wageDepartment: Civilian
  wage: 100 # DS14-value
  #end-backmen: currency

- type: startingGear
  id: MusicianGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    shoes: ClothingShoesBootsLaceup
    id: MusicianPDA
    ears: ClothingHeadsetService
    socks: ClothingUnderwearSocksMusician
  storage:
    back:
    - AcousticGuitarInstrument
    - SaxophoneInstrument

- type: chameleonOutfit
  id: MusicianChameleonOutfit
  job: Musician
  equipment:
    head: ClothingHeadHatTophat
    mask: ClothingMaskBreath
    neck: ClothingMultipleHeadphones
    outerClothing: ClothingOuterWinterMusician
    gloves: ClothingHandsGlovesColorBlack
