- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 15h
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  access:
  - Research
  - Maintenance
  #start-backmen: currency
  minBankBalance: 250
  maxBankBalance: 350
  wageDepartment: Science
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      # DS14-Start
      - type: Skill
        group: LowScience
      # DS14-End

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    socks: ClothingUnderwearSocksResearchAssistant
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
